### ISSUE TITLE
About the recency and the memory controller

### ISSUE THREAD

**Issue by Statisticss** [wbbeyourself/SCM4LLMs#1]
Thank you for this great work!
I have two questions regarding the code.
Q1: In the paper you mentioned that you have used relevance and recency for memory retrieval. But in the code I only found the _similarity() func for relevance calculation. Which part in the code accounts for the recency calculation?

Q2: In the paper you mentioned that the memory controller is responsible for the decision of whether or not to use the summary of memory with the following prompt: 
'''
Given a user command, determine if it can be executed
correctly based solely on the summary historical
information provided. Simply answer yes (A) or no (B),
without explaining the information.
Command: [User Input]
'''
But in the code I can't find this part. So how do you decide when to use summary?

**Comment by wbbeyourself** [comment]
Thank you for your attention!
Regarding the first question about recency, in our initial version, we used this metric. However, subsequent experiments found that we only need to keep the most relevant topk data according to the order of interaction rounds. Recency is implied in the order of rounds.

Regarding the second question: memory controller details
In the SCM4LLMs/core/chat.py file, within the judge_drop_or_summary function.

**Comment by Statisticss** [comment]
Thanks for your quick answer.
But I still don’t understand how recency is implied. In the function get_related_turn(), all the chat history from round 0 to last round are searched to match the query, where the order of interaction rounds doesn't play a role.

And for the judge_drop_or_summary() function, it seems to me that the judge procedure is as following:
(1) If the user query is not answerable with raw text, return 'drop'
(2) If the user query is answerable with summary text, return 'summary'
(3) Otherwise, return 'raw'
This procedure seems different from the one in the paper, where you used a prompt for LLM to make the decision of 'yes (A) or no (B)'. I guess the procedure in the code is a revised version which has better performance?

**Comment by wbbeyourself** [comment]
Reply to question 1 : How recency is implied ?

recency = f(i, L), where i is the turn index of a memory item, L is the total length of memory. 
The function f is forgeting curve function and its value range is (0, 1).  
If i approaches L, then the value of the function f approaches 1; conversely, it approaches 0.

Since rank_score = α * recency_score + β * relevance_score.
α and β are two coefficients, both of which have a range of (0, 1). 
We can adjust the value of the hyperparameter α based on the specific circumstances.

In addition, there are also two papers below that discuss the method of memory update. You can also refer to their code implementation. The titles of the papers are as follows:
[1] Generative Agents: Interactive Simulacra of Human Behavior
[2] MemoryBank: Enhancing Large Language Models with Long-Term Memory


Reply to question 2 : Why memory choie strategy is different from the paper ?

Yes, you are right. The procedure in the code is a revised version just because it has better performance.
We have made modifications to the latest version of the paper. 
However, since we have entered the anonymous period, we are temporarily unable to update the arxiv version. 
We will update it immediately after the review process is completed.

Thank you again for your attention. If you have any further questions, please feel free to contact us at any time.
